/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_header_token1 = 2,
  aux_sym_header_token2 = 3,
  anon_sym_LF = 4,
  sym_docString = 5,
  aux_sym_import_token1 = 6,
  anon_sym_EQ = 7,
  anon_sym_DOT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  sym_length = 12,
  anon_sym_LBRACK_RBRACK = 13,
  aux_sym__primitiveType_token1 = 14,
  aux_sym__primitiveType_token2 = 15,
  aux_sym__primitiveType_token3 = 16,
  aux_sym__primitiveType_token4 = 17,
  aux_sym_bool_token1 = 18,
  aux_sym_bool_token2 = 19,
  aux_sym_int_token1 = 20,
  aux_sym_int_token2 = 21,
  sym_float = 22,
  sym_string = 23,
  sym_none = 24,
  sym_conditional = 25,
  sym_hidden = 26,
  sym_source_file = 27,
  sym_header = 28,
  sym__statement = 29,
  sym__terminator = 30,
  sym_import = 31,
  sym_variableDefinition = 32,
  sym__term = 33,
  sym__expression = 34,
  sym_dotExpression = 35,
  sym_callExpression = 36,
  sym_parameter = 37,
  sym_type = 38,
  sym__arrayType = 39,
  sym__primitiveType = 40,
  sym_bool = 41,
  sym_int = 42,
  sym__scriptFlags = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_header_repeat1 = 45,
  aux_sym_callExpression_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_header_token1] = "header_token1",
  [aux_sym_header_token2] = "header_token2",
  [anon_sym_LF] = "\n",
  [sym_docString] = "docString",
  [aux_sym_import_token1] = "import_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_length] = "length",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [aux_sym__primitiveType_token1] = "_primitiveType_token1",
  [aux_sym__primitiveType_token2] = "_primitiveType_token2",
  [aux_sym__primitiveType_token3] = "_primitiveType_token3",
  [aux_sym__primitiveType_token4] = "_primitiveType_token4",
  [aux_sym_bool_token1] = "bool_token1",
  [aux_sym_bool_token2] = "bool_token2",
  [aux_sym_int_token1] = "int_token1",
  [aux_sym_int_token2] = "int_token2",
  [sym_float] = "float",
  [sym_string] = "string",
  [sym_none] = "none",
  [sym_conditional] = "conditional",
  [sym_hidden] = "hidden",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym__statement] = "_statement",
  [sym__terminator] = "_terminator",
  [sym_import] = "import",
  [sym_variableDefinition] = "variableDefinition",
  [sym__term] = "_term",
  [sym__expression] = "_expression",
  [sym_dotExpression] = "dotExpression",
  [sym_callExpression] = "callExpression",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym__arrayType] = "_arrayType",
  [sym__primitiveType] = "_primitiveType",
  [sym_bool] = "bool",
  [sym_int] = "int",
  [sym__scriptFlags] = "_scriptFlags",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_callExpression_repeat1] = "callExpression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [anon_sym_LF] = anon_sym_LF,
  [sym_docString] = sym_docString,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_length] = sym_length,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [aux_sym__primitiveType_token1] = aux_sym__primitiveType_token1,
  [aux_sym__primitiveType_token2] = aux_sym__primitiveType_token2,
  [aux_sym__primitiveType_token3] = aux_sym__primitiveType_token3,
  [aux_sym__primitiveType_token4] = aux_sym__primitiveType_token4,
  [aux_sym_bool_token1] = aux_sym_bool_token1,
  [aux_sym_bool_token2] = aux_sym_bool_token2,
  [aux_sym_int_token1] = aux_sym_int_token1,
  [aux_sym_int_token2] = aux_sym_int_token2,
  [sym_float] = sym_float,
  [sym_string] = sym_string,
  [sym_none] = sym_none,
  [sym_conditional] = sym_conditional,
  [sym_hidden] = sym_hidden,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym__statement] = sym__statement,
  [sym__terminator] = sym__terminator,
  [sym_import] = sym_import,
  [sym_variableDefinition] = sym_variableDefinition,
  [sym__term] = sym__term,
  [sym__expression] = sym__expression,
  [sym_dotExpression] = sym_dotExpression,
  [sym_callExpression] = sym_callExpression,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym__arrayType] = sym__arrayType,
  [sym__primitiveType] = sym__primitiveType,
  [sym_bool] = sym_bool,
  [sym_int] = sym_int,
  [sym__scriptFlags] = sym__scriptFlags,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_callExpression_repeat1] = aux_sym_callExpression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_docString] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_import_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__primitiveType_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bool_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bool_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_int_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_int_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_none] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_hidden] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_variableDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_dotExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_callExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__arrayType] = {
    .visible = false,
    .named = true,
  },
  [sym__primitiveType] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym__scriptFlags] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callExpression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 25,
  [30] = 30,
  [31] = 28,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 27,
  [41] = 33,
  [42] = 39,
  [43] = 43,
  [44] = 38,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 37,
  [49] = 49,
  [50] = 50,
  [51] = 32,
  [52] = 52,
  [53] = 53,
  [54] = 26,
  [55] = 36,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 66,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '"', 3,
        '(', 40,
        ')', 42,
        ',', 41,
        '-', 27,
        '.', 39,
        '0', 44,
        '=', 38,
        '[', 4,
      );
      if (lookahead == '\\') SKIP(30);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(65);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(70);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '\\') SKIP(1);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 18:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 30:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 31:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') SKIP(32);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ')') ADVANCE(42);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '0') ADVANCE(44);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '\\') SKIP(31);
      if (lookahead == '{') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_header_token2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_docString);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_int_token1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_int_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_int_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_int_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_conditional);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_hidden);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(2);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(3);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(4);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(5);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(7);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(10);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(12);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(16);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__primitiveType_token3);
      END_STATE();
    case 24:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__primitiveType_token1);
      END_STATE();
    case 30:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_none);
      END_STATE();
    case 35:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_bool_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_bool_token2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__primitiveType_token2);
      END_STATE();
    case 40:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(44);
      END_STATE();
    case 41:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_import_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_length);
      END_STATE();
    case 46:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__primitiveType_token4);
      END_STATE();
    case 48:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 49:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_header_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 32},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 32},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 32},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [aux_sym_header_token2] = ACTIONS(1),
    [sym_docString] = ACTIONS(1),
    [aux_sym_import_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_length] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [aux_sym__primitiveType_token1] = ACTIONS(1),
    [aux_sym__primitiveType_token2] = ACTIONS(1),
    [aux_sym__primitiveType_token3] = ACTIONS(1),
    [aux_sym__primitiveType_token4] = ACTIONS(1),
    [aux_sym_bool_token1] = ACTIONS(1),
    [aux_sym_bool_token2] = ACTIONS(1),
    [aux_sym_int_token1] = ACTIONS(1),
    [aux_sym_int_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_none] = ACTIONS(1),
    [sym_conditional] = ACTIONS(1),
    [sym_hidden] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_header] = STATE(5),
    [aux_sym_header_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_RPAREN,
    ACTIONS(11), 1,
      aux_sym_int_token1,
    ACTIONS(13), 1,
      aux_sym_int_token2,
    ACTIONS(17), 1,
      sym_string,
    STATE(40), 1,
      sym_parameter,
    ACTIONS(9), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(15), 2,
      sym_float,
      sym_none,
    STATE(30), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [35] = 9,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      aux_sym_int_token1,
    ACTIONS(13), 1,
      aux_sym_int_token2,
    ACTIONS(17), 1,
      sym_string,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_parameter,
    ACTIONS(9), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(15), 2,
      sym_float,
      sym_none,
    STATE(30), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [70] = 8,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      aux_sym_int_token1,
    ACTIONS(13), 1,
      aux_sym_int_token2,
    ACTIONS(17), 1,
      sym_string,
    STATE(53), 1,
      sym_parameter,
    ACTIONS(9), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(15), 2,
      sym_float,
      sym_none,
    STATE(30), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [102] = 8,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      aux_sym_import_token1,
    STATE(56), 1,
      sym__primitiveType,
    STATE(58), 1,
      sym_type,
    STATE(61), 1,
      sym__arrayType,
    STATE(6), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(46), 2,
      sym_import,
      sym_variableDefinition,
    ACTIONS(23), 5,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [133] = 8,
    ACTIONS(25), 1,
      aux_sym_import_token1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym__primitiveType,
    STATE(58), 1,
      sym_type,
    STATE(61), 1,
      sym__arrayType,
    STATE(7), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(46), 2,
      sym_import,
      sym_variableDefinition,
    ACTIONS(23), 5,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [164] = 8,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      aux_sym_import_token1,
    STATE(56), 1,
      sym__primitiveType,
    STATE(58), 1,
      sym_type,
    STATE(61), 1,
      sym__arrayType,
    STATE(7), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(46), 2,
      sym_import,
      sym_variableDefinition,
    ACTIONS(31), 5,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [195] = 7,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(41), 1,
      aux_sym_int_token1,
    ACTIONS(43), 1,
      aux_sym_int_token2,
    ACTIONS(47), 1,
      sym_string,
    ACTIONS(39), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(45), 2,
      sym_float,
      sym_none,
    STATE(43), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [224] = 7,
    ACTIONS(11), 1,
      aux_sym_int_token1,
    ACTIONS(13), 1,
      aux_sym_int_token2,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_string,
    ACTIONS(9), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(51), 2,
      sym_float,
      sym_none,
    STATE(34), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [253] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      sym_docString,
    ACTIONS(57), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [268] = 3,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_docString,
    ACTIONS(63), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [283] = 3,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      sym_docString,
    ACTIONS(69), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [298] = 3,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym_docString,
    ACTIONS(75), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [313] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [325] = 5,
    ACTIONS(83), 1,
      aux_sym_header_token2,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__terminator,
    ACTIONS(87), 2,
      sym_conditional,
      sym_hidden,
    STATE(20), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [343] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [355] = 2,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [367] = 2,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [379] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [391] = 4,
    ACTIONS(97), 1,
      anon_sym_LF,
    STATE(10), 1,
      sym__terminator,
    ACTIONS(99), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [406] = 4,
    ACTIONS(101), 1,
      anon_sym_LF,
    STATE(11), 1,
      sym__terminator,
    ACTIONS(103), 2,
      sym_conditional,
      sym_hidden,
    STATE(22), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [421] = 4,
    ACTIONS(105), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__terminator,
    ACTIONS(99), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [436] = 3,
    ACTIONS(107), 1,
      anon_sym_LF,
    ACTIONS(109), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [448] = 3,
    ACTIONS(112), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [460] = 2,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [469] = 1,
    ACTIONS(118), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [475] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_callExpression_repeat1,
  [485] = 3,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(126), 1,
      sym_length,
    STATE(51), 1,
      sym_callExpression,
  [495] = 3,
    ACTIONS(114), 1,
      anon_sym_LF,
    ACTIONS(128), 1,
      anon_sym_DOT,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
  [505] = 2,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [513] = 3,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(138), 1,
      sym_length,
    STATE(32), 1,
      sym_callExpression,
  [523] = 1,
    ACTIONS(140), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [529] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [539] = 2,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(144), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [547] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [557] = 1,
    ACTIONS(151), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [563] = 1,
    ACTIONS(153), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [569] = 1,
    ACTIONS(155), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [575] = 1,
    ACTIONS(157), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [581] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_callExpression_repeat1,
  [591] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [601] = 2,
    ACTIONS(157), 1,
      anon_sym_LF,
    ACTIONS(163), 1,
      anon_sym_DOT,
  [608] = 2,
    ACTIONS(165), 1,
      anon_sym_LF,
    ACTIONS(167), 1,
      anon_sym_DOT,
  [615] = 2,
    ACTIONS(155), 1,
      anon_sym_LF,
    ACTIONS(169), 1,
      anon_sym_DOT,
  [622] = 2,
    ACTIONS(171), 1,
      anon_sym_LF,
    ACTIONS(173), 1,
      anon_sym_EQ,
  [629] = 2,
    ACTIONS(175), 1,
      anon_sym_LF,
    STATE(14), 1,
      sym__terminator,
  [636] = 2,
    ACTIONS(177), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym__terminator,
  [643] = 2,
    ACTIONS(153), 1,
      anon_sym_LF,
    ACTIONS(179), 1,
      anon_sym_DOT,
  [650] = 2,
    ACTIONS(181), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__terminator,
  [657] = 2,
    ACTIONS(183), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__terminator,
  [664] = 2,
    ACTIONS(140), 1,
      anon_sym_LF,
    ACTIONS(185), 1,
      anon_sym_DOT,
  [671] = 2,
    ACTIONS(187), 1,
      anon_sym_LF,
    STATE(17), 1,
      sym__terminator,
  [678] = 1,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [683] = 2,
    ACTIONS(118), 1,
      anon_sym_LF,
    ACTIONS(189), 1,
      anon_sym_DOT,
  [690] = 2,
    ACTIONS(151), 1,
      anon_sym_LF,
    ACTIONS(191), 1,
      anon_sym_DOT,
  [697] = 2,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(195), 1,
      anon_sym_LBRACK_RBRACK,
  [704] = 1,
    ACTIONS(197), 1,
      sym_identifier,
  [708] = 1,
    ACTIONS(199), 1,
      sym_identifier,
  [712] = 1,
    ACTIONS(201), 1,
      sym_identifier,
  [716] = 1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
  [720] = 1,
    ACTIONS(193), 1,
      sym_identifier,
  [724] = 1,
    ACTIONS(205), 1,
      anon_sym_LF,
  [728] = 1,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
  [732] = 1,
    ACTIONS(209), 1,
      sym_identifier,
  [736] = 1,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
  [740] = 1,
    ACTIONS(211), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 133,
  [SMALL_STATE(7)] = 164,
  [SMALL_STATE(8)] = 195,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 253,
  [SMALL_STATE(11)] = 268,
  [SMALL_STATE(12)] = 283,
  [SMALL_STATE(13)] = 298,
  [SMALL_STATE(14)] = 313,
  [SMALL_STATE(15)] = 325,
  [SMALL_STATE(16)] = 343,
  [SMALL_STATE(17)] = 355,
  [SMALL_STATE(18)] = 367,
  [SMALL_STATE(19)] = 379,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 406,
  [SMALL_STATE(22)] = 421,
  [SMALL_STATE(23)] = 436,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 460,
  [SMALL_STATE(26)] = 469,
  [SMALL_STATE(27)] = 475,
  [SMALL_STATE(28)] = 485,
  [SMALL_STATE(29)] = 495,
  [SMALL_STATE(30)] = 505,
  [SMALL_STATE(31)] = 513,
  [SMALL_STATE(32)] = 523,
  [SMALL_STATE(33)] = 529,
  [SMALL_STATE(34)] = 539,
  [SMALL_STATE(35)] = 547,
  [SMALL_STATE(36)] = 557,
  [SMALL_STATE(37)] = 563,
  [SMALL_STATE(38)] = 569,
  [SMALL_STATE(39)] = 575,
  [SMALL_STATE(40)] = 581,
  [SMALL_STATE(41)] = 591,
  [SMALL_STATE(42)] = 601,
  [SMALL_STATE(43)] = 608,
  [SMALL_STATE(44)] = 615,
  [SMALL_STATE(45)] = 622,
  [SMALL_STATE(46)] = 629,
  [SMALL_STATE(47)] = 636,
  [SMALL_STATE(48)] = 643,
  [SMALL_STATE(49)] = 650,
  [SMALL_STATE(50)] = 657,
  [SMALL_STATE(51)] = 664,
  [SMALL_STATE(52)] = 671,
  [SMALL_STATE(53)] = 678,
  [SMALL_STATE(54)] = 683,
  [SMALL_STATE(55)] = 690,
  [SMALL_STATE(56)] = 697,
  [SMALL_STATE(57)] = 704,
  [SMALL_STATE(58)] = 708,
  [SMALL_STATE(59)] = 712,
  [SMALL_STATE(60)] = 716,
  [SMALL_STATE(61)] = 720,
  [SMALL_STATE(62)] = 724,
  [SMALL_STATE(63)] = 728,
  [SMALL_STATE(64)] = 732,
  [SMALL_STATE(65)] = 736,
  [SMALL_STATE(66)] = 740,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 6, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 6, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 7, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 7, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 8, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 8, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotExpression, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_callExpression_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callExpression_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotExpression, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 5, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [203] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arrayType, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_papyrusSSE(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "papyrusSSE",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
