/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_header_token1 = 2,
  aux_sym_header_token2 = 3,
  anon_sym_LF = 4,
  sym_docString = 5,
  aux_sym_import_token1 = 6,
  anon_sym_DOT = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  sym_pureAssignment = 11,
  anon_sym_LBRACK_RBRACK = 12,
  aux_sym__primitiveType_token1 = 13,
  aux_sym__primitiveType_token2 = 14,
  aux_sym__primitiveType_token3 = 15,
  aux_sym__primitiveType_token4 = 16,
  aux_sym_bool_token1 = 17,
  aux_sym_bool_token2 = 18,
  aux_sym_int_token1 = 19,
  aux_sym_int_token2 = 20,
  sym_float = 21,
  sym_string = 22,
  sym_none = 23,
  sym_length = 24,
  sym_conditional = 25,
  sym_hidden = 26,
  sym_source_file = 27,
  sym_header = 28,
  sym__terminator = 29,
  sym__term = 30,
  sym_parameter = 31,
  sym__statement = 32,
  sym_import = 33,
  sym_variableDefinition = 34,
  sym_functionCall = 35,
  sym__expression = 36,
  sym_dotExpression = 37,
  sym_callExpression = 38,
  sym_type = 39,
  sym__arrayType = 40,
  sym__primitiveType = 41,
  sym_bool = 42,
  sym_int = 43,
  sym__scriptFlags = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_header_repeat1 = 46,
  aux_sym_callExpression_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_header_token1] = "header_token1",
  [aux_sym_header_token2] = "header_token2",
  [anon_sym_LF] = "\n",
  [sym_docString] = "docString",
  [aux_sym_import_token1] = "import_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_pureAssignment] = "pureAssignment",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [aux_sym__primitiveType_token1] = "_primitiveType_token1",
  [aux_sym__primitiveType_token2] = "_primitiveType_token2",
  [aux_sym__primitiveType_token3] = "_primitiveType_token3",
  [aux_sym__primitiveType_token4] = "_primitiveType_token4",
  [aux_sym_bool_token1] = "bool_token1",
  [aux_sym_bool_token2] = "bool_token2",
  [aux_sym_int_token1] = "int_token1",
  [aux_sym_int_token2] = "int_token2",
  [sym_float] = "float",
  [sym_string] = "string",
  [sym_none] = "none",
  [sym_length] = "length",
  [sym_conditional] = "conditional",
  [sym_hidden] = "hidden",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym__terminator] = "_terminator",
  [sym__term] = "_term",
  [sym_parameter] = "parameter",
  [sym__statement] = "_statement",
  [sym_import] = "import",
  [sym_variableDefinition] = "variableDefinition",
  [sym_functionCall] = "functionCall",
  [sym__expression] = "_expression",
  [sym_dotExpression] = "dotExpression",
  [sym_callExpression] = "callExpression",
  [sym_type] = "type",
  [sym__arrayType] = "_arrayType",
  [sym__primitiveType] = "_primitiveType",
  [sym_bool] = "bool",
  [sym_int] = "int",
  [sym__scriptFlags] = "_scriptFlags",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_callExpression_repeat1] = "callExpression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [anon_sym_LF] = anon_sym_LF,
  [sym_docString] = sym_docString,
  [aux_sym_import_token1] = aux_sym_import_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pureAssignment] = sym_pureAssignment,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [aux_sym__primitiveType_token1] = aux_sym__primitiveType_token1,
  [aux_sym__primitiveType_token2] = aux_sym__primitiveType_token2,
  [aux_sym__primitiveType_token3] = aux_sym__primitiveType_token3,
  [aux_sym__primitiveType_token4] = aux_sym__primitiveType_token4,
  [aux_sym_bool_token1] = aux_sym_bool_token1,
  [aux_sym_bool_token2] = aux_sym_bool_token2,
  [aux_sym_int_token1] = aux_sym_int_token1,
  [aux_sym_int_token2] = aux_sym_int_token2,
  [sym_float] = sym_float,
  [sym_string] = sym_string,
  [sym_none] = sym_none,
  [sym_length] = sym_length,
  [sym_conditional] = sym_conditional,
  [sym_hidden] = sym_hidden,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym__terminator] = sym__terminator,
  [sym__term] = sym__term,
  [sym_parameter] = sym_parameter,
  [sym__statement] = sym__statement,
  [sym_import] = sym_import,
  [sym_variableDefinition] = sym_variableDefinition,
  [sym_functionCall] = sym_functionCall,
  [sym__expression] = sym__expression,
  [sym_dotExpression] = sym_dotExpression,
  [sym_callExpression] = sym_callExpression,
  [sym_type] = sym_type,
  [sym__arrayType] = sym__arrayType,
  [sym__primitiveType] = sym__primitiveType,
  [sym_bool] = sym_bool,
  [sym_int] = sym_int,
  [sym__scriptFlags] = sym__scriptFlags,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_callExpression_repeat1] = aux_sym_callExpression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_docString] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_import_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pureAssignment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__primitiveType_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__primitiveType_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bool_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bool_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_int_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_int_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_none] = {
    .visible = true,
    .named = true,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_hidden] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_variableDefinition] = {
    .visible = true,
    .named = true,
  },
  [sym_functionCall] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_dotExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_callExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__arrayType] = {
    .visible = false,
    .named = true,
  },
  [sym__primitiveType] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym__scriptFlags] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callExpression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 25,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 28,
  [41] = 31,
  [42] = 32,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 39,
  [49] = 49,
  [50] = 36,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 27,
  [55] = 26,
  [56] = 37,
  [57] = 33,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '"', 3,
        '(', 39,
        ')', 41,
        ',', 40,
        '-', 27,
        '.', 38,
        '0', 44,
        '=', 42,
        '[', 4,
      );
      if (lookahead == '\\') SKIP(30);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(65);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(70);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '=') ADVANCE(42);
      if (lookahead == '\\') SKIP(1);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 18:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(12);
      END_STATE();
    case 25:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 30:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 31:
      if (eof) ADVANCE(33);
      if (lookahead == '\n') SKIP(32);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '0') ADVANCE(44);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '\\') SKIP(31);
      if (lookahead == '{') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_header_token2);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_docString);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_pureAssignment);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_int_token1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_int_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_int_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_int_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x17f ||
          lookahead == 0x212a) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_conditional);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_hidden);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(2);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(3);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(4);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(5);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(7);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(10);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(12);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(16);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__primitiveType_token3);
      END_STATE();
    case 24:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__primitiveType_token1);
      END_STATE();
    case 30:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_none);
      END_STATE();
    case 35:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_bool_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_bool_token2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__primitiveType_token2);
      END_STATE();
    case 40:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(44);
      END_STATE();
    case 41:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_import_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_length);
      END_STATE();
    case 46:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__primitiveType_token4);
      END_STATE();
    case 48:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 49:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_header_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 32},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 32},
  [43] = {.lex_state = 32},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 32},
  [63] = {.lex_state = 32},
  [64] = {.lex_state = 32},
  [65] = {.lex_state = 32},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 32},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [aux_sym_header_token2] = ACTIONS(1),
    [sym_docString] = ACTIONS(1),
    [aux_sym_import_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_pureAssignment] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [aux_sym__primitiveType_token1] = ACTIONS(1),
    [aux_sym__primitiveType_token2] = ACTIONS(1),
    [aux_sym__primitiveType_token3] = ACTIONS(1),
    [aux_sym__primitiveType_token4] = ACTIONS(1),
    [aux_sym_bool_token1] = ACTIONS(1),
    [aux_sym_bool_token2] = ACTIONS(1),
    [aux_sym_int_token1] = ACTIONS(1),
    [aux_sym_int_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_none] = ACTIONS(1),
    [sym_length] = ACTIONS(1),
    [sym_conditional] = ACTIONS(1),
    [sym_hidden] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_header] = STATE(2),
    [aux_sym_header_token1] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      aux_sym_import_token1,
    STATE(43), 1,
      sym__primitiveType,
    STATE(60), 1,
      sym_callExpression,
    STATE(62), 1,
      sym__arrayType,
    STATE(63), 1,
      sym_type,
    STATE(5), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(49), 3,
      sym_import,
      sym_variableDefinition,
      sym_functionCall,
    ACTIONS(11), 4,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
  [37] = 9,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      aux_sym_int_token1,
    ACTIONS(21), 1,
      aux_sym_int_token2,
    ACTIONS(25), 1,
      sym_string,
    STATE(28), 1,
      sym_parameter,
    ACTIONS(17), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(23), 2,
      sym_float,
      sym_none,
    STATE(29), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [72] = 10,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      aux_sym_import_token1,
    STATE(43), 1,
      sym__primitiveType,
    STATE(60), 1,
      sym_callExpression,
    STATE(62), 1,
      sym__arrayType,
    STATE(63), 1,
      sym_type,
    STATE(4), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(49), 3,
      sym_import,
      sym_variableDefinition,
      sym_functionCall,
    ACTIONS(35), 4,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
  [109] = 10,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      aux_sym_import_token1,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    STATE(43), 1,
      sym__primitiveType,
    STATE(60), 1,
      sym_callExpression,
    STATE(62), 1,
      sym__arrayType,
    STATE(63), 1,
      sym_type,
    STATE(4), 2,
      sym__statement,
      aux_sym_source_file_repeat1,
    STATE(49), 3,
      sym_import,
      sym_variableDefinition,
      sym_functionCall,
    ACTIONS(11), 4,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
  [146] = 9,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      aux_sym_int_token1,
    ACTIONS(21), 1,
      aux_sym_int_token2,
    ACTIONS(25), 1,
      sym_string,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_parameter,
    ACTIONS(17), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(23), 2,
      sym_float,
      sym_none,
    STATE(29), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [181] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      aux_sym_int_token1,
    ACTIONS(21), 1,
      aux_sym_int_token2,
    ACTIONS(25), 1,
      sym_string,
    STATE(46), 1,
      sym_parameter,
    ACTIONS(17), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(23), 2,
      sym_float,
      sym_none,
    STATE(29), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [213] = 7,
    ACTIONS(19), 1,
      aux_sym_int_token1,
    ACTIONS(21), 1,
      aux_sym_int_token2,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(46), 1,
      sym_string,
    ACTIONS(17), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(44), 2,
      sym_float,
      sym_none,
    STATE(38), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [242] = 7,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(52), 1,
      aux_sym_int_token1,
    ACTIONS(54), 1,
      aux_sym_int_token2,
    ACTIONS(58), 1,
      sym_string,
    ACTIONS(50), 2,
      aux_sym_bool_token1,
      aux_sym_bool_token2,
    ACTIONS(56), 2,
      sym_float,
      sym_none,
    STATE(44), 6,
      sym__term,
      sym__expression,
      sym_dotExpression,
      sym_callExpression,
      sym_bool,
      sym_int,
  [271] = 3,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_docString,
    ACTIONS(62), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [286] = 3,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      sym_docString,
    ACTIONS(68), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [301] = 3,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      sym_docString,
    ACTIONS(74), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [316] = 3,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      sym_docString,
    ACTIONS(80), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [331] = 2,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [343] = 5,
    ACTIONS(84), 1,
      aux_sym_header_token2,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(10), 1,
      sym__terminator,
    ACTIONS(88), 2,
      sym_conditional,
      sym_hidden,
    STATE(20), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [361] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [373] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [385] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [397] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 6,
      aux_sym_import_token1,
      aux_sym__primitiveType_token1,
      aux_sym__primitiveType_token2,
      aux_sym__primitiveType_token3,
      aux_sym__primitiveType_token4,
      sym_identifier,
  [409] = 4,
    ACTIONS(102), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__terminator,
    ACTIONS(104), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [424] = 4,
    ACTIONS(106), 1,
      anon_sym_LF,
    STATE(11), 1,
      sym__terminator,
    ACTIONS(108), 2,
      sym_conditional,
      sym_hidden,
    STATE(22), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [439] = 4,
    ACTIONS(110), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__terminator,
    ACTIONS(104), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [454] = 3,
    ACTIONS(112), 1,
      anon_sym_LF,
    ACTIONS(114), 2,
      sym_conditional,
      sym_hidden,
    STATE(23), 2,
      sym__scriptFlags,
      aux_sym_header_repeat1,
  [466] = 3,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_pureAssignment,
    ACTIONS(117), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [478] = 2,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [487] = 1,
    ACTIONS(123), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [493] = 1,
    ACTIONS(125), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [499] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym_callExpression_repeat1,
  [509] = 2,
    ACTIONS(131), 1,
      anon_sym_DOT,
    ACTIONS(133), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [517] = 2,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 2,
      anon_sym_LBRACK_RBRACK,
      sym_identifier,
  [525] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [535] = 3,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(143), 1,
      sym_length,
    STATE(33), 1,
      sym_callExpression,
  [545] = 1,
    ACTIONS(145), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [551] = 3,
    ACTIONS(117), 1,
      anon_sym_LF,
    ACTIONS(147), 1,
      anon_sym_DOT,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
  [561] = 3,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [571] = 1,
    ACTIONS(156), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [577] = 1,
    ACTIONS(158), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [583] = 2,
    ACTIONS(131), 1,
      anon_sym_DOT,
    ACTIONS(160), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [591] = 1,
    ACTIONS(162), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [597] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_callExpression_repeat1,
  [607] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_callExpression_repeat1,
  [617] = 3,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(170), 1,
      sym_length,
    STATE(57), 1,
      sym_callExpression,
  [627] = 2,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK_RBRACK,
  [634] = 2,
    ACTIONS(176), 1,
      anon_sym_LF,
    ACTIONS(178), 1,
      anon_sym_DOT,
  [641] = 2,
    ACTIONS(180), 1,
      anon_sym_LF,
    STATE(17), 1,
      sym__terminator,
  [648] = 1,
    ACTIONS(154), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [653] = 2,
    ACTIONS(182), 1,
      anon_sym_LF,
    ACTIONS(184), 1,
      sym_pureAssignment,
  [660] = 2,
    ACTIONS(162), 1,
      anon_sym_LF,
    ACTIONS(186), 1,
      anon_sym_DOT,
  [667] = 2,
    ACTIONS(188), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__terminator,
  [674] = 2,
    ACTIONS(156), 1,
      anon_sym_LF,
    ACTIONS(190), 1,
      anon_sym_DOT,
  [681] = 2,
    ACTIONS(192), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym__terminator,
  [688] = 2,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(14), 1,
      sym__terminator,
  [695] = 2,
    ACTIONS(196), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__terminator,
  [702] = 2,
    ACTIONS(125), 1,
      anon_sym_LF,
    ACTIONS(198), 1,
      anon_sym_DOT,
  [709] = 2,
    ACTIONS(123), 1,
      anon_sym_LF,
    ACTIONS(200), 1,
      anon_sym_DOT,
  [716] = 2,
    ACTIONS(158), 1,
      anon_sym_LF,
    ACTIONS(202), 1,
      anon_sym_DOT,
  [723] = 2,
    ACTIONS(145), 1,
      anon_sym_LF,
    ACTIONS(204), 1,
      anon_sym_DOT,
  [730] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [734] = 1,
    ACTIONS(208), 1,
      sym_identifier,
  [738] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [742] = 1,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
  [746] = 1,
    ACTIONS(172), 1,
      sym_identifier,
  [750] = 1,
    ACTIONS(212), 1,
      sym_identifier,
  [754] = 1,
    ACTIONS(214), 1,
      sym_identifier,
  [758] = 1,
    ACTIONS(216), 1,
      sym_identifier,
  [762] = 1,
    ACTIONS(218), 1,
      anon_sym_LF,
  [766] = 1,
    ACTIONS(220), 1,
      sym_identifier,
  [770] = 1,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 146,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 213,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 271,
  [SMALL_STATE(11)] = 286,
  [SMALL_STATE(12)] = 301,
  [SMALL_STATE(13)] = 316,
  [SMALL_STATE(14)] = 331,
  [SMALL_STATE(15)] = 343,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 373,
  [SMALL_STATE(18)] = 385,
  [SMALL_STATE(19)] = 397,
  [SMALL_STATE(20)] = 409,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 439,
  [SMALL_STATE(23)] = 454,
  [SMALL_STATE(24)] = 466,
  [SMALL_STATE(25)] = 478,
  [SMALL_STATE(26)] = 487,
  [SMALL_STATE(27)] = 493,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 509,
  [SMALL_STATE(30)] = 517,
  [SMALL_STATE(31)] = 525,
  [SMALL_STATE(32)] = 535,
  [SMALL_STATE(33)] = 545,
  [SMALL_STATE(34)] = 551,
  [SMALL_STATE(35)] = 561,
  [SMALL_STATE(36)] = 571,
  [SMALL_STATE(37)] = 577,
  [SMALL_STATE(38)] = 583,
  [SMALL_STATE(39)] = 591,
  [SMALL_STATE(40)] = 597,
  [SMALL_STATE(41)] = 607,
  [SMALL_STATE(42)] = 617,
  [SMALL_STATE(43)] = 627,
  [SMALL_STATE(44)] = 634,
  [SMALL_STATE(45)] = 641,
  [SMALL_STATE(46)] = 648,
  [SMALL_STATE(47)] = 653,
  [SMALL_STATE(48)] = 660,
  [SMALL_STATE(49)] = 667,
  [SMALL_STATE(50)] = 674,
  [SMALL_STATE(51)] = 681,
  [SMALL_STATE(52)] = 688,
  [SMALL_STATE(53)] = 695,
  [SMALL_STATE(54)] = 702,
  [SMALL_STATE(55)] = 709,
  [SMALL_STATE(56)] = 716,
  [SMALL_STATE(57)] = 723,
  [SMALL_STATE(58)] = 730,
  [SMALL_STATE(59)] = 734,
  [SMALL_STATE(60)] = 738,
  [SMALL_STATE(61)] = 742,
  [SMALL_STATE(62)] = 746,
  [SMALL_STATE(63)] = 750,
  [SMALL_STATE(64)] = 754,
  [SMALL_STATE(65)] = 758,
  [SMALL_STATE(66)] = 762,
  [SMALL_STATE(67)] = 766,
  [SMALL_STATE(68)] = 770,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 6, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 6, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 7, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 7, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 8, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 8, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primitiveType, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotExpression, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_callExpression_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callExpression_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callExpression, 5, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variableDefinition, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 5, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_callExpression, 4, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotExpression, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arrayType, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functionCall, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_papyrusSSE(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "papyrusSSE",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
